name = "exercism_test_runner"
version = "1.7.0"
description = "A test framework for Gleam exercises on Exercism"
licences = ["Apache-2.0"]
repository = { type = "github", user = "exercism", repo = "gleam-test-runner" }
links = [{ title = "Website", href = "https://exercism.org/tracks/gleam" }]
gleam = ">= 0.32.0"

[dependencies]
gap = "~> 1.0"
glance = "~> 0.8 or ~> 1.0"
gleam_erlang = "~> 0.19 or ~> 1.0"
gleam_json = "~> 0.5 or ~> 1.0"
gleam_stdlib = "~> 0.33 or ~> 1.0"
simplifile = "~> 1.0"
gleam_community_ansi = "~> 1.1"
argv = "~> 1.0"

[dev-dependencies]
